# Copyright 2023 The MathWorks, Inc.

name: Build and Publish the Container Image

# images build with this workflow are created with the following naming conventions:
  # ${base_image_name}:${matlab_release}-${os}


# Trigger this workflow either manually or when a new change is pushed to the
# repo (except .md files)
on:
  workflow_call:
    inputs:
      docker_build_context:
        description: 'relative path to folder with Dockerfile. Ex: ./matlab-deps/r2023a/ubuntu20.04 '
        required: true
        type: string
      base_image_name:
        description: 'Name of base image. Example: mathworks/matlab-deps'
        required: true
        type: string
      matlab_release_tag:
        description: 'Name of matlab release. Example: r2023a'
        required: true
        type: string
      os_info_tag:
        description: 'Allowed values: aws-batch, ubi8, ubi9, ubuntu20.04 ubuntu22.04'
        required: true
        type: string
      should_add_latest_tag:
        description: 'Specify if this image should also be tagged as latest'
        required: true
        type: boolean

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & Push Image
        if: ${{ inputs.should_add_latest_tag == false }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.docker_build_context }}
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ inputs.base_image_name }}:${{ inputs.matlab_release_tag }}-${{ inputs.os_info_tag }}
      
      - name: Build & Push Image with latest Tag
        if: ${{ inputs.should_add_latest_tag == true }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.docker_build_context }}
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ inputs.base_image_name }}:${{ inputs.matlab_release_tag }}-${{ inputs.os_info_tag }}
            ghcr.io/${{ inputs.base_image_name }}:latest

